kitMenu:
  title: "Choose a kit"
joinMenu:
  title: "Join a raid"
teamMenu:
  title: "Select a team"
buildMenu:
  items:
    - DIRT
    - STONE
    - SAND
gameSettings:
  preGameCountdown: 15 # Seconds
  buildPhaseDuration: 15 # Minutes
  raidPhaseDuration: 15 # Minutes
  killReward: 20 # Dollars
  winReward: 500 # Dollars